//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WorldBuild.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_ATTRIBUTE                   107
#define IDR_MAINFRAME                   128
#define IDR_WorldBuildTYPE              129
#define IDD_NEW                         130
#define IDD_TERRAIN                     132
#define IDD_MAIN_TAB                    133
#define IDD_GRASS                       134
#define IDD_GRASS_SETTING               135
#define IDD_WATER                       136
#define IDD_ENTITY                      137
#define IDD_PARTICLE                    138
#define IDD_ACTOR                       139
#define IDD_MAP_CELL                    140
#define IDC_NEW_HIGHTMAP                1003
#define IDC_NEW_WORLD_SIZE              1004
#define IDC_NEW_MAX_HIGHT               1005
#define IDC_NEW_ROW_SIZE                1006
#define IDC_NEW_MATERIAL                1007
#define IDC_TR_LAYERS                   1016
#define IDC_TR_DECAL                    1017
#define IDC_TR_SMOOTH                   1018
#define IDC_TR_SINK                     1019
#define IDC_TR_HEAVE                    1020
#define IDC_MT_TAB                      1022
#define IDC_TR_BRUSH_SIZE               1023
#define IDC_TR_BRUSH_DENSITY            1024
#define IDC_TR_BRUSH_DENSITY_TXT        1025
#define IDC_TR_BRUSH_SIZE_TXT           1026
#define IDC_MT_BATCH                    1027
#define IDC_MT_PRIMITIVE                1028
#define IDC_MT_FPS                      1029
#define IDC_GRASS_LIST                  1032
#define IDC_GT_LOAD                     1033
#define IDC_GT_ADD                      1035
#define IDC_GT_LOCK                     1036
#define IDC_GT_DELETE                   1037
#define IDC_GT_SELECT                   1038
#define IDC_GT_SETTING                  1041
#define IDC_GSS_ROW                     1044
#define IDC_GSS_COLUMN                  1045
#define IDC_GSS_SIZE                    1046
#define IDC_GSS_MATERIAL                1047
#define IDC_WT_LOAD                     1051
#define IDC_WT_SETTING                  1052
#define IDC_WT_ADD                      1053
#define IDC_WT_SELECT                   1054
#define IDC_WT_LOCK                     1055
#define IDC_WT_DELETE                   1056
#define IDC_WT_LIST                     1057
#define IDC_LIST1                       1058
#define IDC_ET_LIST                     1058
#define IDC_PT_LIST                     1058
#define IDC_ACTOR_MODEL_LIST            1058
#define IDC_ET_CLEAR                    1060
#define IDC_ET_APPEND                   1061
#define IDC_ET_ADD                      1062
#define IDC_ET_SELECT                   1063
#define IDC_ET                          1064
#define IDC_ET_LOCK                     1064
#define IDC_PT_APPEND                   1065
#define IDC_PT_CLEAR                    1066
#define IDC_PT_ADD                      1067
#define IDC_PT_SELECT                   1068
#define IDC_PT_LOCK                     1069
#define IDC_ATTRI_NAME                  1073
#define IDC_ATTRI_FILE                  1075
#define IDC_ATTRI_POS_X                 1076
#define IDC_ATTRI_POS_Y                 1077
#define IDC_ATTRI_POS_Z                 1078
#define IDC_ATTRI_ORT_X                 1079
#define IDC_ATTRI_ORT_Y                 1080
#define IDC_ATTRI_ORT_Z                 1081
#define IDC_ATTRI_ORT_W                 1082
#define IDC_ATTRI_SCL_X                 1083
#define IDC_ATTRI_SCL_Y                 1084
#define IDC_ATTRI_SCL_Z                 1085
#define IDC_ATTRI_TYPE                  1086
#define IDC_ET_TRANSLATE                1087
#define IDC_ET_ROTATE                   1088
#define IDC_ET_SCALE                    1089
#define IDC_ET_X                        1093
#define IDC_ET_Y                        1094
#define IDC_ET_Z                        1095
#define IDC_ET_X_INC                    1096
#define IDC_ET_X_DEC                    1097
#define IDC_ET_Y_INC                    1098
#define IDC_ET_Y_DEC                    1099
#define IDC_ET_Z_INC                    1100
#define IDC_ET_Z_DEC                    1101
#define IDC_ET_DELETE                   1103
#define IDC_BUTTON1                     1104
#define IDC_ACTOR_DELETE                1104
#define IDC_MAP_Y_INC                   1104
#define IDC_ACTOR_LIST                  1105
#define IDC_ACTOR_SELECT                1106
#define IDC_ACTOR_LOCK                  1107
#define IDC_ACTOR_EDIT                  1108
#define IDC_ACTOR_ADD                   1109
#define IDC_MAP_DISPLAY_SIZE            1110
#define IDC_MAP_BRUSH_SIZE              1111
#define IDC_MAP_WIDTH                   1112
#define IDC_MAP_HEIGHT                  1113
#define IDC_MAP_DC_TRUE                 1114
#define IDC_MAP_DC_FASLE                1115
#define IDC_MAP_ACTIVE                  1116
#define IDC_MAP_LOCK                    1117
#define IDC_MAP_INSERT                  1118
#define IDC_MAP_CLEAR                   1119
#define IDC_BUTTON2                     1120
#define IDC_MAP_Y_DEC                   1120
#define IDC_FILE_NEW                    32771
#define IDC_FILE_OPEN                   32772
#define IDC_FILE_SAVE                   32773
#define ID_32774                        32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1121
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
